name: build-images

on:
  schedule:
    - cron: '0 4 * * *' # everyday at 4am
  push:
    branches: master

jobs:
  build-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build images
        run: |
          docker buildx build \
            --build-arg LMS_VERSION=7.9.2 \
            --tag syphr/logitechmediaserver:7.9.2 \
            --tag syphr/logitechmediaserver:latest \
            --platform linux/amd64,linux/arm/v7 \
            --push \
            .
      - name: Cleanup
        run: rm -f ${HOME}/.docker/config.json
  build-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build images
        run: |
          for version in "7.9.3" "8.0.0"; do
            docker buildx build \
              --build-arg LMS_VERSION="${version}" \
              --tag syphr/logitechmediaserver:"${version}-beta" \
              --tag syphr/logitechmediaserver:latest \
              --platform linux/amd64,linux/arm/v7 \
              --push \
              .
          done
      - name: Cleanup
        run: rm -f ${HOME}/.docker/config.json
