name: build images

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build images
        run: |
          docker buildx build \
            --build-arg LMS_VERSION=7.9.2 \
            --tag syphr/logitechmediaserver:7.9.2 \
            --tag syphr/logitechmediaserver:latest \
            --platform linux/amd64,linux/arm/v7 \
            --push
            .
